### ISSUE TITLE
Hard fail on `load()`: incompatible validator post-deserialisation

### ISSUE THREAD

**Issue by davidhyman** [marshmallow-code/marshmallow#867] opened 2018-07-03 10:07 UTC
# Reproduction

After defining a schema with the following field:
```python
created = DateTime(
    required=True,
    description='Creation time in RFC3339 date-time with UTC time zone.',
    validate=[Regexp(regex=re.compile('^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$'))]
)
```

And passing in an object to `schema().load(data)` where this field has the following value:
```
created='2018-07-02T15:19:58.381000+00:00'
```

# Outcome

We get the following error from the validator:
```shell
lib\site-packages\marshmallow\fields.py:266: in deserialize
    self._validate(output)
lib\site-packages\marshmallow\fields.py:196: in _validate
    r = validator(value)
lib\site-packages\marshmallow\validate.py:320: in __call__
    if self.regex.match(value) is None:
E   TypeError: expected string or bytes-like object
```

# Expected behaviour

What I'd expect is for this error to be caught and added to `self.errors`, whereas instead, the exception escapes.

# Discussion

As to how/why this happens; our schema is defining a specific sub-format of RFC3339. Marshmallow performs deserialisation, and then validation:

```python
# lib\site-packages\marshmallow\fields.py:266: in deserialize
output = self._deserialize(value, attr, data)  # value is now a datetime instance
self._validate(output)  # boom!
```
I'd expect the validator to fail with this *particular* input anyway, because it doesn't match the regex - but that's not the issue here.

Is there another functionality or pattern within marshmallow that allows this kind of behaviour? Perhaps a way to mark a validator as 'before deserialisation'?

```python
# lib\site-packages\marshmallow\fields.py:266: in deserialize
self._validate(value, pre_deserialization=True)  # maybe boom!?
output = self._deserialize(value, attr, data)  # value is now a datetime instance
self._validate(output)  # maybe boom!?
```

Is this worth a separate feature request? [specifically: "mechanism for pre-deserialisation validators"]

Thanks!

**Comment by lafrech** [comment] 2018-07-03 10:17
Duplicate of https://github.com/marshmallow-code/marshmallow/issues/399.

You can define a custom field for this.

**Comment by davidhyman** [comment] 2018-07-03 13:40
@lafrech Thanks for the pointer. Perhaps a custom field would solve the 'pre-deserialisation' validator issue (inconsequentially, as I am using it in conjunction with OpenAPI specs it wouldn't resolve my specific use case).

I maintain that validation flow errors should not escape from marshmallow (even if the validator is badly configured).

Perhaps any error in a validator could be re-raised as a `ValidationError` to ensure it is caught by the rest of the machinery? Or is the philosophy that validation failures are always a failure resulting in an explicit raise of `ValidationError`, and anything else raised in the validator/configuration itself should escape because it's probably unintended?

e.g. this sample for reference, from UUID. Any error not explicitly handled in this code would result in an escape from the validation system:
```python
        try:
            return uuid.UUID(value)
        except (ValueError, AttributeError):
            self.fail('invalid_uuid')
```
e.g. by passing some reference that does something different with `.replace` (admittedly contrived as this isn't likely from any literals / AST objects):
```python
import uuid
class X:
    replace = False
uuid.UUID(X())

>>> TypeError: 'bool' object is not callable
```

**Comment by davidhyman** [comment] 2018-07-06 12:01
This issue *could* still occur in Marshmallow >3, but the specifics of the examples above are outdated (see, for example http://marshmallow.readthedocs.io/en/latest/_modules/marshmallow/fields.html#UUID._deserialize)

**Comment by sloria** [comment] 2019-08-02 04:39
> Or is the philosophy that validation failures are always a failure resulting in an explicit raise of ValidationError, and anything else raised in the validator/configuration itself should escape because it's probably unintended?

This. We don't want to re-raise any and all exceptions as ValidationErrors. At the very least, this would result in strange, inconsistent error messages. At worst, it could expose sensitive data from exceptions to clients.

I think either a custom field or a `@pre_load` method address the OP.

**Closed as completed by sloria** 2019-08-02 04:39 UTC
