### ISSUE TITLE
Enveloping of marshaled objects

### ISSUE THREAD

**Issue by Ch00k** [marshmallow-code/marshmallow#81] opened 2014-12-05 11:34 UTC
It looks like marshmallow does not allow enveloping serialized objects automatically. Something like this:

``` json
{
    "imdb_data": {
        "country": "UK, USA, Canada, China", 
        "director": "Sergey Bodrov", 
        "genre": "Adventure, Family, Fantasy", 
        "id": 1121096, 
        "rating": null, 
        "title": "Seventh Son"
        }
}
```

You have to manually do enveloping by wrapping the `MarshalResult.data` in the envelope you want: `jsonify({"imdb_data": result.data})`. Would it make sense to support such a thing by passing a kwarg to `Schema.dump`?

**Comment by sloria** [comment] 2014-12-05 13:36
Duplicate of #69 . See the docs here: http://marshmallow.readthedocs.org/en/latest/extending.html#transforming-data, which show 2 ways to meet this use case.

**Closed as completed by sloria** 2014-12-05 13:36 UTC
