### ISSUE TITLE
Incorrect "required" validation in marshmallow.fields.Nested

### ISSUE THREAD

**Issue by maximkulkin** [marshmallow-code/marshmallow#495] opened 2016-07-12 21:58 UTC
``` python
class UserSchema(Schema):
    name = fields.String()

class BlogSchema(Schema):
    user = fields.Nested(UserSchema, required=True)

_, errs = BlogSchema().load({})
assert 'user' in errs
assert errs['user'] == [fields.Field.default_error_messages['required']]
```

This works fine, error is reported for 'user' attribute in blog:
`{'user': [u'Missing data for required field.']}`

Although, this works differently (notice "required=True" for "name" field in UserSchema):

``` python
class UserSchema(Schema):
    name = fields.String(required=True)

class BlogSchema(Schema):
    user = fields.Nested(UserSchema, required=True)

_, errs = BlogSchema().load({})
assert 'user' in errs
assert errs['user'] == [fields.Field.default_error_messages['required']]
```

Resulting errors look like this:
`{'user': {'name': [u'Missing data for required field.']}}`
This looks even more ridiculous if your errors are even more deeply nested.

I think that error should appear only if you do this:

``` python
_, errs = BlogSchema().load({'user': {}})
```

and for previous case the correct errors should be "required" error for "user" attribute of blog.

**Comment by deckar01** [comment] 2016-07-14 13:58
Duplicate of #319.

**Closed as completed** 2017-01-08 19:44 UTC
