### ISSUE TITLE
Schema.validate does not return errors on None data

### ISSUE THREAD

**Issue by xrmx** [marshmallow-code/marshmallow#1031] opened 2018-10-30 09:57 UTC
Hello, am building my first project with marshmallow and found that if i pass None as data to Schema.validate i do not get errors. I find this quite counter intuitive because it will means i have to validate the data before passing it to a validator :) I can't find any reference to it in the documentation, is this the intended behaviour?

With marshmallow 2.16.1 this raises and AssertionError:
```
from marshmallow import Schema, fields

class FooSchema(Schema):
    foo = fields.String(required=True)

schema = FooSchema()
errors = schema.validate(None)
assert errors
```

**Comment by lafrech** [comment] 2018-10-30 10:22
Hi. Welcome to marshmallow.

This is a duplicate of https://github.com/marshmallow-code/marshmallow/issues/511, which I fixed in https://github.com/marshmallow-code/marshmallow/pull/725, merged in marshmallow 3 branch.

**Closed as completed by lafrech** 2018-10-30 10:22 UTC

**Comment by xrmx** [comment] 2018-10-30 10:37
Ah, missed the issue. Any chance that the change can be backported to 2.x? Otherwise will try to move to marshmallow 3. Thanks!

**Comment by lafrech** [comment] 2018-10-30 10:41
It won't be backported. It would be a breaking change.

You can add a check in your code or move to MA3. For a starting project, I'd pick MA3.
