### ISSUE TITLE
fields.List проблема с load_default. Value caching

### ISSUE THREAD

**Issue by Timkar164** [marshmallow-code/marshmallow#2120] opened 2023-04-22 11:22 UTC
So, I ran into a problem when working with marshmallow.fields.List, according to the documentation, the `load_default` parameter can take both a value and a callable object. I expected the behavior that in the absence of the required field, and the declaration of `marshmallow.fields.List(marshmallow.fields.Str(),allow_none=True,load_default=[])` to get an object with an empty array. Yes, it works if the array doesn't change during the lifetime of any of the objects created with `marshmallow.Schema` (see `human1` and `human2`). However, if a value is added to the array as a result of the script, then in the next load_default, in the absence of the required field, it will substitute the array that the last created object had. The code of the question is below, pay attention when changing `human3,` the value from his array will go `to` human4, and their total array will go to human5, this happens as a result of `MyClassSchema,` `**data` already contains the wrong array. I tried calling `MyClassSchema().load(data1)` and creating/deleting an instance of `MyClassSchema()` for example `_schema=MyClassSchema()` `_schema.load(data1)` - this also leads to an error. The example with `human6` shows that no error occurs when passing this field

    
    class MyClass(object):
      def __init__(self,name: str, mylist: list):
        self.name = name
        self.mylist = mylist
        
      def subscribe(self,value):
        if not (value in self.mylist):
            self.mylist.append(value)
        else:
            print(f"value: {value} cannot subscribe")
            
    import marshmallow
    print(f"version marshmallow is: {marshmallow.__version__}")
    class MyClassSchema(marshmallow.Schema):
        name = marshmallow.fields.Str()
        mylist = marshmallow.fields.List(marshmallow.fields.Str(),allow_none=True,load_default=[])
        @marshmallow.post_load
        def make(self, data, **kwargs):
            print(f"marshmallow data to create class:  {data}")
            return MyClass(**data)
        
    data1 = {
      "name": "Alex"}

    data2 = {
      "name": "Bob"}

    data3 = {
      "name": "Tima",
      "mylist": ["string_tima_1"]}

    print("\nBuild first human class")
    human1 = MyClassSchema().load(data1)
    print(human1)
    print(human1.__dict__)

    print("\nBuild second human class")
    human2 = MyClassSchema().load(data2)
    print(human2)
    print(human2.__dict__)

    print("\nBuild third human class")
    human3 = MyClassSchema().load(data1)
    print(human3)
    print(human3.__dict__)
    human3.subscribe('string_1')
    print(human3.__dict__)
 
    print("\nBuild fourth human class")
    human4 = MyClassSchema().load(data2)
    print(human4)
    print(human4.__dict__)
    human4.subscribe('string_2')
    print(human4.__dict__)

    print("\nBuild sixth human class")
    human5 = MyClassSchema().load(data2)
    print(human5)
    print(human5.__dict__)

    print("\nBuild fifth human class")
    human6 = MyClassSchema().load(data3)
    print(human6)
    print(human6.__dict__)

the output and visual demonstration can be found below

    from datetime import date
    version marshmallow is: 3.19.0

    Build first human class
    marshmallow data to create class:  {'name': 'Alex', 'mylist': []}
    <__main__.MyClass object at 0x00000190D5DEE340>
    {'name': 'Alex', 'mylist': []}

    Build second human class
    marshmallow data to create class:  {'name': 'Bob', 'mylist': []}
    <__main__.MyClass object at 0x00000190D5DEE460>
    {'name': 'Bob', 'mylist': []}

    Build third human class
    marshmallow data to create class:  {'name': 'Alex', 'mylist': []}
    <__main__.MyClass object at 0x00000190D5DEEEE0>
    {'name': 'Alex', 'mylist': []}
    {'name': 'Alex', 'mylist': ['string_1']}

    Build fourth human class
    marshmallow data to create class:  {'name': 'Bob', 'mylist': ['string_1']}
    <__main__.MyClass object at 0x00000190D5DEED30>
    {'name': 'Bob', 'mylist': ['string_1']}
    {'name': 'Bob', 'mylist': ['string_1', 'string_2']}

    Build sixth human class
    marshmallow data to create class:  {'name': 'Bob', 'mylist': ['string_1', 'string_2']}
    <__main__.MyClass object at 0x00000190D5DEEC10>
    {'name': 'Bob', 'mylist': ['string_1', 'string_2']}

    Build fifth human class
    marshmallow data to create class:  {'name': 'Tima', 'mylist': ['string_tima_1']}
    <__main__.MyClass object at 0x00000190D5DEEAF0>
    {'name': 'Tima', 'mylist': ['string_tima_1']}

I have several solutions to this problem that I use now. The first is to change `marshmallow.fields.List(marshmallow.fields.Str(),allow_none=True,load_default=[])` to `marshmallow.fields.List(marshmallow.fields.Str(),allow_none=True,load_default=list)`, the second is to change the schema to ``marshmallow.fields.List(marshmallow.fields.Str(),allow_none=True,load_default=None)`` and change the class attribute `self.mylist = list() if mylist == None else mylist` . However, I would like to understand the reason for this problem, because in my program I use more complex data structures involving `fields.list` and I wanted to be sure of the reliability of this method. I do not understand why the class that the schema returns affects its further work. I tried to fix this by instantiating the schema whenever I wanted to call it and deleting it afterwards, but that didn't work. So, this is my first issue on github, I hope for help in finding the cause of the occurrence. Have a good day.

**Comment by lafrech** [comment] 2023-04-23 19:56
Duplicate of #2114.

**Closed as completed by lafrech** 2023-04-23 19:56 UTC
