### ISSUE TITLE
JSON deserialization converts dots in field names to deep dictionaries.

### ISSUE THREAD

**Issue by rbu** [marshmallow-code/marshmallow#1506] opened 2020-02-04 14:25 UTC
**Summary**
The marshmallow JSON deserializer interprets dots as meaning a sub-object in user-provided input, violating the JSON standard.

**Minimal example**
```py
from marshmallow import Schema, INCLUDE

class MySchema(Schema):
    class Meta:
        unknown = INCLUDE

> s = MySchema()
> s.load({"01.12.2019": 1, "01.01.2020": 0})
{'01': {'01': {'2020': 0}, '12': {'2019': 1}}}

> s.loads("""{"01.12.2019": 1, "01.01.2020": 0}""")
{'01': {'01': {'2020': 0}, '12': {'2019': 1}}}
```

**Discussion**
While I appreciate the idea of allowing "compact notation" using dotted paths, this even causes problems in attribute/data_key specifications, such as #1225 (I like the idea discussed there of using lists of strings instead of in-band signaling using path notation). Either way, applying the dot path transformation *on the data* is counter-intuitive, undocumented and dangerous as it's hard to discover during testing.

**Motivation**
My schema allows somewhat "free form" key-value attributes for certain objects (think os.environ, or some other meta-attribute table). The schema (in my case) enforces that all field values are numeric, like so:
```
class MetaAttributeSchema(Schema):
    class Meta:
        unknown = INCLUDE

    @validates_schema
    def validate_types(self, data, **kwargs):
        errors = {}
        for key, value in data.items():
            try:
                NumberValidator.deserialize(value)
            except ValidationError as e:
                errors[key] = e.messages
        if errors:
            raise ValidationError(errors)
```

**Comment by deckar01** [comment] 2020-02-04 16:03
I can repro this in 3.4.0 and 3.0.0. I am unable to reproduce this behavior in 2.20.5..

I think this behavior has been around for a while, but it was just unreachable until `unknown=EXCLUDE`. `data_key` appears to behave correctly.

```py
from marshmallow import Schema, fields

class Test(Schema):
    y = fields.Str(data_key='x.y')

Test().load({'x.y': 'test'})
# {'y': 'test'}
```

I suspect this is caused by performing the dot parsing on the field name after resolving the `attribute` option instead of only trying to parse the dots if the attribute option is being used.

---

As a workaround I would suggest using `fields.Dict` if you can. It is not supported as a top-level structure, but if it is nested, it is quite a bit more powerful (and safer) than `unknown=INCLUDE`.

```py
from marshmallow import Schema, fields, INCLUDE

class MySchema(Schema):
    foo = fields.Dict(fields.Date('%m.%d.%Y'), fields.Int)

s = MySchema()
s.load({"foo": {"01.12.2019": 1, "01.01.2020": 0}})
# {'foo': {datetime.date(2019, 1, 12): 1, datetime.date(2020, 1, 1): 0}}
```

**Comment by rbu** [comment] 2020-02-05 11:09
:heart: Thank you @deckar01 for that great hint. I was not  aware of fields.Dict, but it matches much better what I was trying to achieve and does not expose this unexpected behavior. I'll leave the issue open nonetheless as you point out this was not the case in previous versions.

**Comment by adyouri** [comment] 2020-02-09 17:35
@deckar01 Can this be solved by setting the value directly with `ret[key] = value` instead of using `set_value()` [here](https://github.com/marshmallow-code/marshmallow/blob/18bd033f6949ce7c9d5197912d31fdaf02c1b535/src/marshmallow/schema.py#L682)?

From this:
```py
for key in set(data) - fields:
    value = data[key]
    if unknown == INCLUDE:
        set_value(typing.cast(typing.Dict, ret), key, value)
```

To this:

```py
for key in set(data) - fields:
    value = data[key]
    if unknown == INCLUDE:
        ret[key] = value
```
This way the dots won't be converted when `unknown=INCLUDE`.

**Comment by deckar01** [comment] 2020-02-10 16:36
There is another `set_value()` [a few lines above that](https://github.com/marshmallow-code/marshmallow/blob/18bd033f6949ce7c9d5197912d31fdaf02c1b535/src/marshmallow/schema.py#L673), but removing them would regress the feature that allows `attribute` to be dotted. It needs to check `attribute` in a utility method that decides the how to set the attribute. `Field` already has the opposite `get_value()`, so maybe it should also handle `set_value()`.

```py
def set_value(self, obj, attr, value):
    if self.attribute:
        utils.set_value(obj, self.attribute, value)
    else:
        obj[attr] = value
```

**Comment by deckar01** [comment] 2020-02-10 16:37
For reference, this code has been around since https://github.com/marshmallow-code/marshmallow/commit/8d90fb9d67f74a7497437db32b0781f398e8449e (2017), it was just unreachable when the data key was invalid before.

**Closed as completed** 2021-03-30 00:08 UTC
