### ISSUE TITLE
The function decorated by the "post_load" decorator will undergo changes in parameter types as the function name changes.

### ISSUE THREAD

**Issue by LionSniper** [marshmallow-code/marshmallow#2216] opened 2023-12-06 02:49 UTC
`
class AdGroupUpsertSchemaV3(ma.SQLAlchemySchema):
    name = fields.String(required=True)

    class Meta:
        model = models.AdGroup
        fields = 'name'
        load_instance = True

    @post_load
    def a(self, data, *args, **kwargs):
        print(type(data))
        return data
`

flask-marshmallow==0.14.0
marshmallow==3.17.0
marshmallow-sqlalchemy==0.28.1

like the code above，when post_load decorator func name is a-m, data type is dict, when func name is n-z, data type is <class 'modules.advertising.group.models.AdGroup'>

why why why?

**Comment by deckar01** [comment] 2023-12-06 04:09
Duplicate of https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/545. The issue is not in this repo.

**Closed as completed by deckar01** 2023-12-06 04:09 UTC
