### ISSUE TITLE
Could I use a single schema instance on concurrent request?

### ISSUE THREAD

**Issue by yupeng0921** [marshmallow-code/marshmallow#783] opened 2018-04-25 02:31 UTC
For example, I have an AlbumSchema class, then I create a global variable 'g_schema' from it:
g_schema = AlbumSchema()
Could I use the same g_schema on the concurrent http requests? Is it safe?

**Comment by lafrech** [comment] 2018-04-26 07:35
Funny you ask because that very same day we've been facing issues that look quite like concurrency issues.

We use marshmallow + webargs and we pass webargs's `use_args` a `Schema` instance, so the instance is shared over all requests.

Some requests receive an error message that obviously corresponds to another request that occurred concurrently.

This does not occur when passing a schema class.

We're investigating this. The root cause could be the fact that the `Unmarshaller` is [created at init time](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/schema.py#L332):

```python
        #: Callable unmarshalling object
        self._unmarshal = marshalling.Unmarshaller()
```

(same issue with `self._marshal` and perhaps other attributes)

The `Unmarshaller` instance is then shared among all requests and called several times during the loading process, which does not seem thread safe.

I've checked in webargs code and it is meant to receive either a class or an instance, so this looks like a bug.

If this is really the case, then it is a serious show-stopper.

I'm not sure how to isolate/reproduce/fix/test. Help very much welcome.

And if I'm wrong, well... great, what a relief, sorry for the noise.

**Comment by lafrech** [comment] 2018-04-26 07:46
From a quick analysis, I think the consequences are "limited" to spurious error messages.

Take the following with care, I have no certainty at this point:

- When all goes fine, data is not mixed up between two concurrent requests.

- When an error occurs, another concurrent requests can receive the error message meant for the other request.

- A wrong request can not pass due to another concurrent passing request.

So you'd have false positives, but no false negatives.

This would mitigate the issue a bit.

**Comment by lafrech** [comment] 2018-04-26 13:24
It should be noted that this happens only if two concurrent requests occur and one of them fails validation. In the case of a loaded server, as long as all requests are valid, there is no problem.

Also, we managed to see and reproduce this because we're using marshmallow to parse pretty fat inputs. In the general case of normal size inputs, the race condition is much less likely to occur.

**Closed as completed** 2018-05-11 03:00 UTC
Labels: help wanted

**Comment by taion** [comment] 2018-05-15 03:02
Looking at the code, the fix in ~~#799~~ #785 is not quite sufficient. `Schema._update_fields` has some amount of shared state, and can cause issues with stomping on other updates if field types need to be inferred.

**Comment by deckar01** [comment] 2018-05-15 03:36
I'm not sure #799 is the right reference in that comment. Do you mean #785?

**Comment by lafrech** [comment] 2018-05-15 07:01
I think @taion meant the fix in #785. And he provides an example of thread-safety issue in https://github.com/marshmallow-code/marshmallow/issues/809.

**Comment by taion** [comment] 2018-05-15 07:06
oops, sorry – i did mean #785.

and i have a fix in https://github.com/marshmallow-code/marshmallow/pull/810 that would address this issue, though it's worth noting that it's a broader change

**Comment by ThiefMaster** [comment] 2019-03-11 10:58
marshmallow-code/webargs#371 might be the same issue - not sure though, since I don't (manually) create a custom schema there.

**Comment by ckanesan** [comment] 2019-06-17 14:54
Sorry for commenting on a closed issue but I have very similar question concerning the context attribute. Indeed, I'm interested in using a shared schema instance to (un)marshal concurrent http requests and would need to pass request related context data to the load and dump methods. Will there be a race condition on the context attribute?
