### ISSUE TITLE
Customize the unknown=RAISE error message

### ISSUE THREAD

**Issue by rileyjohngibbs** [marshmallow-code/marshmallow#891] opened 2018-07-26 00:03 UTC
Currently when loading an object with an unknown field, if `unknown=RAISE` for the schema, then the error message is "Unknown field." (This is true as well for fields that are defined as `dump_only=True`.)

It would be handy to be able to customize this message, particularly since it's misleading for `dump_only` fields.

**Comment by lafrech** [comment] 2018-07-26 08:17
Duplicate of https://github.com/marshmallow-code/marshmallow/issues/852.

**Closed as completed by lafrech** 2018-07-26 08:17 UTC
