### ISSUE TITLE
Deserialization support is missing

### ISSUE THREAD

**Issue by rmihael** [marshmallow-code/marshmallow#6] opened 2013-12-18 16:40 UTC
I'm not sure if it can be considered as an issue, but I think that supporting deserialization would really benefit marshmallow. 
It's obvious that not every serializer can provide reverse operation, but it's true in many cases. If it's not against your view on what this library should be then I can work on extending marshmallow to support it and prepare pull request.

**Comment by sloria** [comment] 2013-12-18 17:42
I agree that deserialization would be a useful feature as long as the same implementation worked across several ORM objects.  Using marshmallow with an ORM is the intended use case, but marshmallow does not make any decision to support one ORM over another. 

If you'd like to do this, I will gladly review and merge it.

**Comment by sloria** [comment] 2014-08-07 13:30
Deserialization support is underway on the `deserialization` branch: https://github.com/sloria/marshmallow/tree/deserialization. It will be added for the next release (0.8.0)

**Comment by sloria** [comment] 2014-08-09 22:14
Briefly, the proposed API will be as follows:

By default, input data will be deserialized to a dictionary of Python objects.

``` python
from marshmallow import Serializer, fields

class PersonSerializer(Serializer):

    name = fields.String()
    balance = fields.Price()
    created = fields.DateTime()


in_data = {
    'name': 'Steve',
    'balance': '123.4567'
    'created': 'Sat, 09 Aug 2014 18:07:27 -0000',
}

data, errors = PersonSerializer().load(in_data)
# {
#     'name': 'Steve',
#     'balance': '123.46'
#     'created': datetime.datetime(2014, 8, 9, 18, 7, 27, 740940)
# }
```

Serializers can optionally define a `make_object` method which receives the deserialized data and creates the final, deserialized object.

``` python
from mymodels import Person

class PersonSerializer2(Serializer):

    name = fields.String()
    balance = fields.Price()
    created = fields.DateTime()

    def make_object(self, data):
        # data is the same dictionary as ``deserialized`` from the previous example
        return Person(**data)

data, errors = PersonSerializer2().load(in_data)
# <Person(name='Steve')>
```

EDIT 2014-08-16: Update example to current API.

**Comment by jtsoi** [comment] 2014-08-11 14:05
@sloria this is exactly the same way I did in our deserializer API.

Will the Field API also change? Something like field.restore_value(target, key, data) ?

Another question, is updating existing models in scope for deserialization?

/JT

**Comment by sloria** [comment] 2014-08-11 22:07
@jtsoi Yes, the `Field` interface has been refactored. Concrete fields implement `_serialize(self, value, attr_name, obj)`, `_deserialize(self, value)`, and `_format(self, value)`. 

I haven't thought about doing object updates in the deserialzation API. Do you have an interface in mind, or specific use cases that your are thinking of?

**Comment by zerodivisi0n** [comment] 2014-08-29 19:33
As @rmihael mentioned at the beginning, not every serializer can provide reverse operation.
Fields like `created_at`, `updated_at` and others should not be used during deserialization. They can be excluded by defining another serializer or by using a `factory` or `exclude` option. But each of these methods has its disadvantages. It might be worth to add a separate `Meta` options for serialization and deserialization?

**Comment by sloria** [comment] 2014-08-30 22:43
The `exclude` option should not be necessary for deserialization because the the deserialized dictionary will only include those fields that are included in the input to `load`. 

Assuming the same serializer as in my comment above: 

``` python
in_data = {
    'name': 'Steve',
    'balance': '123.4567'
}

ser = PersonSerializer()
ser.load(in_data)
# {
#     'name': 'Steve',
#     'balance': '123.46'
# }
```

Notice that `created` is not included in the final output because it was not included in the input data.

**Comment by zerodivisi0n** [comment] 2014-08-31 06:43
Yes. But what if the client pass the `created` field in input data? It turns out that it can be set to any value to this field.

Another example. `User` serializer has `balance` field, which managed by the server. It must be present in output, but it should not be set by the client.

How to solve this case?

**Comment by sloria** [comment] 2014-08-31 15:10
How about creating separate `Schema` objects (the `Serializer` class was renamed to `Schema`) for serialization and deserialization?

``` python
in_schema = UserSchema(exclude=('date_created', 'balance'))
in_schema.load({'name': 'Monty', 'balance': 999})  # => {'name': 'Monty'}

out_schema = UserSchema()
out_schema.dump(a_user)  # => full output
```

**Comment by sloria** [comment] 2014-09-03 02:18
The deserialization API is now on the `release/1.0` branch. Closing.

**Comment by zerodivisi0n** [comment] 2014-09-15 17:52
Yes, it's a convenient method. Just checked it. But what about serialization of objects collection with `many` option? Create a separate serializer for it, same as `out_schema`, but with `many` option? May be it is worth to add an optional argument `many` to `dump` and `load` methods?

**Comment by sloria** [comment] 2014-09-16 01:17
@zerodivisi0n I was a bit torn on whether to add the `many` parameter to `dump` and `load`. 

The rationale for excluding it is that all configuration for an individual `Schema`'s output (e.g. whether to serialize collections, which fields to include) should go into the constructor. Only the object to be serialized/deserialized gets passed to `dump` and `load`.

Adding the additional `many` parameter may create the false expectation that all configuration parameters (`only`, `exclude`, etc.) may be passed to `dump` and `load`. This would mean that whenever a new parameter is added to the `Schema` constructor, it must also be added in 4 other places: `dump`, `dumps`, `load`, and `loads`. 

Furthermore, adding those parameters then removing them in the future would introduce backwards incompatibility. The opposite decision would not.

**Comment by zerodivisi0n** [comment] 2014-09-16 06:04
Yes, Steven, I understand you. You are completely redesign interface in version 1.0. It became clearer and easier but less flexible. But in general, everything is fine. Thanks!

**Closed as completed** 2014-09-17 02:25 UTC
Labels: feedback welcome

**Comment by sakshiaroras** [comment] 2019-11-21 19:26
return_path_recipient_id = fields.Int(missing = 0)
    reply_to_recipient_id = fields.Int(missing = 0)
    from_recipient_id = fields.Int(missing = 0)

i am trying to deserialise if value doesnot exist it gives 0 but it is returning null . how can i achieve

**Comment by deckar01** [comment] 2019-11-21 19:49
@sakshiaroras Your question does not appear to be related to this 6 year old issue. Please open a new issue and provide the complete information required to reproduce your issue.

**Comment by sakshiaroras** [comment] 2019-11-21 19:50
Hi I am new to this and i stuck with very less time can you guide me how i can do

**Comment by deckar01** [comment] 2019-11-21 19:56
Here is a guide on documenting problems in a way that others can reproduce:

https://stackoverflow.com/help/minimal-reproducible-example

Here is the GitHub link to create a new marshmallow issue:

https://github.com/marshmallow-code/marshmallow/issues/new
