### ISSUE TITLE
Selecting the data getting sourced to the field

### ISSUE THREAD

**Issue by kpagcha** [marshmallow-code/marshmallow#979] opened 2018-10-04 13:11 UTC
I have a class `MyClass` and items are related to it somehow, but are not accessible through `obj.items` but rather a method `obj.get_items()` and let's say it requires some arguments, etc. The point is that the schema can't just load `obj.items` because it doesn't exist, we need `obj.get_items(*args)`.

How can we indicate what the source of the field is when declaring it?

```
class MySchema(Schema):
    objects = fields.Nested(ItemSchema, ???????=lambda obj: obj.get_items(*args))
```

How can I do this?

**Comment by deckar01** [comment] 2018-10-04 13:21
This seems like a duplicate of the issue you entered 30 minutes ago. 

https://github.com/marshmallow-code/marshmallow/issues/978

I encourage you to read through the documentation. There are examples they may show a similar use case and API docs if you need to dig into the capabilities of a specific class.

https://marshmallow.readthedocs.io/

**Comment by lafrech** [comment] 2018-10-04 13:23
I suppose you could subclass `Schema` and override [get_attribute](https://github.com/marshmallow-code/marshmallow/blob/dev/marshmallow/schema.py#L388) to use a function of yours rather than `utils.get_value`.

**Comment by kpagcha** [comment] 2018-10-04 13:28
@deckar01 it is not a duplicate. Here I am asking how to define the source of the field data. In the other one I am asking about the ability to access and process field data AFTER it is loaded in the schema but before dumping. They may seem related but they are entirely different questions.

I have spent the whole morning going through the documentation and the API reference, but I have not managed to figure out a solution to any of my questions, that is why I resorted to asking here.

**Comment by kpagcha** [comment] 2018-10-04 13:29
@lafrech I see. But would that require having to subclass `Schema` every time I need to specify how to get the field source value? That seems awfully bloated. I suspect I will need to do it for multiple schemas.

**Comment by deckar01** [comment] 2018-10-04 13:54
> > **data_key** (str) – The name of the key to get the value from when deserializing.
> 
> https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.fields.Field
> 
> I think you might need to use the `Function` field.
> 
> > A field that takes the value returned by a function.
> 
> https://marshmallow.readthedocs.io/en/3.0/api_reference.html#marshmallow.fields.Function
> 
> Can you provide an example of what the data looks like before loading, and what you would like it to look like after dumping?

https://github.com/marshmallow-code/marshmallow/issues/978#issuecomment-427014373

Without an example of the data you are trying to load it is difficult to provide an example that composes these capabilities to satisfy your use case.

**Comment by kpagcha** [comment] 2018-10-04 14:16
I am going to use the same example I just posted in the other issue:

```
class Competition(models.Model):
	name = models.CharField()
	# ...

class Game(models.Model):
	competition = models.ForeignKey('Competition')
	player1 = models.ForeignKey('Player')
	player2 = models.ForeignKey('Player')
	court = models.ForeignKey('Court', null=True)
	start = models.DateTimeField(null=True)
	end = models.DateTimeField(null=True)
	# ...

class GameSchema(Schema):
	# using just id for simplicity in the example, but it would have other fields (Str, Nested...)
	id = fields.Int()

class CompetitionSchema(Schema):
	name = fields.Str()
	games = fields.Nested(GameSchema, many=True)
```

The scenario is this: as you can notice, the `Competition` class has no `games` attribute. They are instead accessed this way: `competition.game_set.all()`. What I need is a way to tell the schema to look for the value of the field in the place I explicitly point at, be it `competition.game_set.all()` or anything else containing `Game` objects matching the `GameSchema`. I want to tell the `Schema` class "hey, use THIS value I am giving you to populate your fields instead of looking for `games` yourself".

**Comment by deckar01** [comment] 2018-10-04 14:26
Duplicate of #978

**Comment by deckar01** [comment] 2018-10-04 14:28
Let's try to keep this discussion on the original issue for now. If there are still unresolved issues after that one is closed we can reopen this one.

**Closed as completed** 2018-10-04 14:27 UTC
Labels: question
