### ISSUE TITLE
Validate known fields and keep unknown fields?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [marshmallow-code/marshmallow#747] opened 2018-03-01 12:16 UTC
Hi, I have a use case where I have a defined schema with some fields that need to be validated, and other fields that are "unknown" (a json document of this type has over 700 fields in various nesting levels) and does not need validation but need to be serialized and deserialized. Is this something that is possible with marshmallow? I could not find an answer for this specific use case in the docs. I saw #127 but this is not quite what I need. I need to validate everything defined in the schema and let it pass anything that is not defined.

Thanks!

**Comment by ghost** [comment] 2018-03-05 15:24
I was just looking for a similar feature.  For evolvability, it would be handy to have a way to have access to all field/values that weren't handled by the deserialization process to allow handling after the fact.

**Comment by ramnes** [comment] 2018-03-16 17:27
See that PR and @sloria's answer: https://github.com/marshmallow-code/marshmallow/pull/595

**Comment by lafrech** [comment] 2018-04-11 19:59
Closing as duplicate of https://github.com/marshmallow-code/marshmallow/issues/718.

If the feature described in there was added, this could be achieved by adding

```python
    class Meta:
        additional_properties = fields.Raw()
```

to the `Schema`, for instance.

In the meantime, you should be able to achieve this with a post_load method: it receives both `result` and `original_data`, so you can complete `result` with `original_data`. I believe this answers @rlubke's comment.

Please react if I'm wrong and I can reopen.

**Closed as completed by lafrech** 2018-04-11 19:59 UTC

**Comment by sloria** [comment] 2018-07-05 12:14
It is now possible to keep unknown fields in 3.0.0b12.

https://marshmallow.readthedocs.io/en/3.0/quickstart.html#handling-unknown-fields

See #853 for a proposal to specify an output field for unknown fields.

**Comment by ghost** [comment] 2018-07-06 15:52
This is good to see.  Looking at the docs, it's unclear to me how the unknown fields are stored and how they can be used.  

For example, if we're using this option, and I deser an entity that has unknown fields, if I serialize the same instance again, are those unknown fields inserted into the stream automatically?

**Comment by JordanSimba** [comment] 2021-02-12 13:06
@sloria  probably a little late, but just ran into this now... ended up doing something like this

```
class Model:
    def __init__(self, field1: str,  **kwargs) -> None:
        self.field1: str = sender

        for name, val in kwargs.items():
            setattr(self, name, val) 


class ModelSchema(Schema):
    class Meta:
        unknown = INCLUDE

    field1 = fields.Str(required=True)
```
