### ISSUE TITLE
Is there a way to combine SQLAlchemy with Marshmallow for deserializing incoming JSON structure into a DB object for storage?

### ISSUE THREAD

**Issue by sarimmehdi** [marshmallow-code/marshmallow#1930] opened 2021-12-30 15:32 UTC
I have to store a database object. This is how I define it:

```
class SomeData(db.Model):
    id = db.Column(db.String(100), primary_key=True)
    some_id = db.Column(db.String(100))
    another_id = db.Column(db.String(100))
    valid_for_something = db.Column(db.Boolean)
```

I am receiving this object from a mobile app, so I set up my REST API. I am using webargs which makes use of Marshmallow. So, I defined the schema for SomeData as follows:

```
class SomeDataArgs(Schema):
    some_id = fields.Str(validate=some_id_valid_func, required=True)
    another_id = fields.Str(validate=another_id_valid_func, required=True)
    valid_for_something = fields.Bool(required=True)
```

Then, I define the REST API call to validate and store this object in my server's database as follows:

```
@use_kwargs(SomeDataArgs)
def post(some_id, another_id, valid_for_something):
    data = SomeData(some_id=some_id, 
                    another_id=another_id, 
                    valid_for_something=valid_for_something)
    db.session.add(data)
    db.session.commit()
    return '', 201
```

So, my question is: Is there a way to just declare one class that validates the incoming data and also allows me to store it in my SQLAlchemy database immediately after validation? Below, I would describe an ideal solution that:

I just declare one class for validation and DB storage:

```
class SomeData(InheritsFromBothMarshmallowAndSQLAlchemy): 
    # set by sqlalchemy when I add SomeData to my db 
    id = db.Column(db.String(100), primary_key=True)

     # these fields get validated by marshmallow and then added to my db object
     some_id = fields.Str(validate=some_id_valid_func, required=True)
     another_id = fields.Str(validate=another_id_valid_func, required=True)
     valid_for_something = fields.Bool(required=True)
```

And then just declare my REST API function like this:

```
@some_decorator(SomeData) def post(data_object): 
    # so, the data object has the same structure as defined in SomeData class 
    # as soon as I receive it here, I do immediate validation and add it to my 
    # db if it is a valid object 
    db.session.add(data_object) 
    db.session.commit() 
    return '', 201
```

I hope my question is clear, I would basically like to have one SomeData class instead of having two (one for adding to database and one for use with webargs to validate the incoming structure)

**Comment by deckar01** [comment] 2021-12-30 18:24
https://marshmallow-sqlalchemy.readthedocs.io/en/latest/

**Comment by sarimmehdi** [comment] 2021-12-31 03:17
@deckar01 can show me how the above can be used in my case without creating two separate classes for essentially the same object. My goal is to avoid code duplicity. I am unable to see how marshmallow-sqlalchemy can do that or maybe I am misreading the documentation.

**Comment by deckar01** [comment] 2021-12-31 17:24
This appears to be a duplicate of https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/128. I would encourage you to continue the discussion there, or open a new issue at https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/ if you would like to propose a feature.

@sloria I can't move this issue. It might be related to me missing some repo invites which are now expired. 😴

**Comment by sarimmehdi** [comment] 2021-12-31 19:43
I have opened the [issue](https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/423)

**Comment by lafrech** [comment] 2022-01-01 19:58
Closing as duplicate of https://github.com/marshmallow-code/marshmallow-sqlalchemy/issues/423.

**Closed as completed by lafrech** 2022-01-01 19:58 UTC
