### ISSUE TITLE
QuerySelect fields encourage slow code

### ISSUE THREAD

**Issue by jmcarp** [marshmallow-code/marshmallow#227] opened 2015-06-20 14:45 UTC
The `_serialize` and `_deserialize` methods of the `QuerySelect` and `QuerySelectList` fields are slow by design and should only be used for small cursors, if at all. Both methods load data (presumably from an ORM) row by row into Python, compare some key of that row against `value`, and continue if the keys are different. This type of work is almost always orders of magnitude faster when pushed to the underlying database: compare iterating over a large cursor in Python versus a `WHERE` query on an indexed column in SQLAlchemy / SQL.

Users may not realize that the implementation of these fields can easily cause poor performance. For example, use of these fields in marshmallow-sqlalchemy is currently causing relationship fields load the entire foreign table on every call to `_serialize` or `_deserialize`. I propose that these fields either add a warning in the documentation explaining that they are unsuitable for large result sets and should be used with care (and a query profiler!), or be removed from core altogether. Reading over the discussion around the original PR, I think this kind of field makes much more sense when written on a per-ORM basis and maintained in a separate library--like marshmallow-sqlalchemy or smore.

**Comment by philtay** [comment] 2015-06-20 16:16
Currently `QuerySelect` is O(n) and `QuerySelectList` is O(n^2) - these behaviours are intended. These fields are not meant to be used when thousands of rows are involved, especially `QuerySelectList`. Their "classic" use case is to (de)serialize and validate against a (relatively) small set of results. See [WTForms](https://github.com/wtforms/wtforms/blob/master/wtforms/ext/sqlalchemy/fields.py) for another implementation of this kind.

Designing a _generic_ SQLAlchemy field able to push the value to (de)serialize directly into _any_ user-provided query would be awesome but definitely not an easy task. I'm against removing these fieds. At least until a better, but equally generic, alternative surfaces.

**Comment by jmcarp** [comment] 2015-06-20 22:50
- Running N or N^2 queries is a bad idea when one would be enough.
- I don't see anything in the docs indicating that `QuerySelect` is not intended for use with large result sets--hence the subject of the issue.
- The WTForms implementation only runs the query once per field object, after which the results are cached. This implementation doesn't, meaning that potentially N or N^2 queries are run for _each_ de/serialize call.
- It's helpful to know more about your use case, but now I'm thinking these classes mix up what should be separate concerns. One is validation, which I think would be handled better using (no surprise here) a validator. The other is loading data via ORM on deserializing, which makes more sense if written separately per ORM, and moved to a separate library. See http://www.django-rest-framework.org/api-guide/relations for examples.

**Comment by jmcarp** [comment] 2015-06-21 02:29
It's also worth pointing out that the WTForms implementation makes at most one query, not N or N^2.

**Comment by philtay** [comment] 2015-06-21 02:39
- These fields don't "run N or N^2 queries". They just iterate over a result set and the query itself is executed only a single time. N is the length of this result set. If the query you pass to the `query` parameter retrieves 10^6 results then it will be "slow". But this is true in general, not only in this case. You should always be careful about the queries you throw at the DB, big result sets mean big lists and poor performance. Nothing special or new here. IMO this is the best you can do without losing generality. But, if somehow, you are able to code a field that pushes the value to (de)serialize directly in the user-provided query, I will do anything I can to help. I'd love to see something like that in marshmallow.
- We could add a warning, why not. But again - avoiding big result sets is a common best practice. If you use an ORM, almost always you will end up iterating over a list of results - in a way or another, marshmallow or not marshmallow.
- The problem is not the query. The cached result set is iterated again and again in WTForms too. Anyway, while adding a caching layer doesn't solve this problem, it creates a new one: cache invalidation. Moreover most ORMs already have an internal cache.
- No, "validation" here is meant as a mere check of presence of a given key in the result set. It's naturally done during (de)serialization. Using an external validator (like `OneOf`) will simply double the execution time. Anyway there is room for improvement here. By relaxing a requirement (without causing any harm IMO), there is a way to implement O(1) - constant time - serialization, but not deserialization. Regarding the "separate library" idea. Can you post a more efficient SQLAlchemy-specific field? One that can work with _any kind_ of query (i.e. push the value to (de)serialize to a generic query of any complexity that can have multiple and different SQL clauses to filter the result set, subqueries, joins, composite primary keys, etc.). Consider that even if the docs say that `QuerySelect` and `QuerySelectList` are ORM-agnostic (and they are) I always had in mind SQLAlchemy during their implementation. Again, FWIW, if you are really going to undertake this effort you can count on my help.

**Comment by philtay** [comment] 2015-06-22 16:52
@sloria after this discussion, last night, I had an epiphany. I'm still not 100% sure, but most probably I know how to implement a field which offloads all the hard work to the DB. No more algorithmic complexity Python-side. The trick is to use a query template (or factory if you will) and an optional pre-validator. I can make them ORM-agnostic, but they won't be compatible with the current `QuerySelect` and `QuerySelectList` at all. Let me know if you are interested.

**Comment by sloria** [comment] 2015-07-08 01:35
@philtay Would you mind sharing a gist?

**Comment by philtay** [comment] 2015-07-09 22:48
@sloria please find below a VERY rough POC. This is only to show you the idea. If you like it we can discuss the details or I can directly open a PR during the weekend. Let me know.

``` python
class Query(Field):
    def __init__(self, query_factory, key_field, key_getter):
        self.query_factory = query_factory
        self.key_field = key_field
        self.key_getter = key_getter

    def _deserialize(self, value):
        key = self.key_field.deserialize(value)
        result = self.query_factory(key)

        if result is None:
            raise ValidationError('Invalid key')

    def _serialize(self, value):
        key = self.key_getter(value)
        return self.key_field.serialize(key)


class User(Model):
    id = Column(Integer, primary_key=True)
    username = Column(String(80))

class MySchema(Schema):
    user = fields.Query(
        query_factory = lambda n: session.query(User).filter_by(id=n).one(),
        key_field = fields.Int(),
        key_getter = 'id'
    )
```

EDIT: small fix in `_serialize`

**Comment by philtay** [comment] 2015-07-27 15:29
@sloria, any thoughts? i posted my idea as per your request 18 days ago

**Comment by sloria** [comment] 2015-07-28 12:31
Apologies for the delay. I will try to look at this close over the weekend.

**Comment by philtay** [comment] 2015-08-26 18:39
@sloria hoping you have enjoyed the looooong weekend ;) seriously, this would introduce a breaking change. it's something to push before 2.0. do you want these improved query fields?

**Comment by sloria** [comment] 2015-08-27 03:50
Again, sorry for the delay. I'm going to hold off on making changes to the current Query fields. There are multiple ways to write them, and I'm still not sure they belong in marshmallow core. For the time being, I'll add a warning in the docs and leave more optimized implementations up to external packages.

**Comment by philtay** [comment] 2015-08-27 12:34
@sloria ok, if you wish i could add them [here](https://github.com/marshmallow-code/marshmallow-sqlalchemy/blob/dev/marshmallow_sqlalchemy/fields.py).

**Comment by sloria** [comment] 2015-09-01 00:51
marshmallow-sqlalchemy already has the `Related` field, so I'm not sure the generic Query fields are necessary.

**Comment by philtay** [comment] 2015-09-02 03:57
@sloria ok, as you wish. anyway, i still feel that improvements can (and should) be made. now a pedantic note - the two warnings you recently committed should read something along these lines:

`The (de)serialization of this field has an algorithmic complexity of O(N), where N is the number of query results.`

`The (de)serialization of this field has an algorithmic complexity of O(N*M), where N is the number of query results and M is the length of the list to (de)serialize.`

**Comment by sloria** [comment] 2015-09-11 02:41
For now, the current QuerySelect and QuerySelectList fields are deprecated. We may revisit them in the future, but I agree with @jmcarp that these kinds of fields belong in separate libraries.

**Closed as completed by sloria** 2015-09-11 02:41 UTC
