### ISSUE TITLE
get_value awkwardness with Django RelatedManager objects

### ISSUE THREAD

**Issue by johtso** [marshmallow-code/marshmallow#397] opened 2016-02-18 11:30 UTC
After upgrading to the latest version of marshmallow, I had some breakages due to the changed behaviour of `get_value`, namely this commit https://github.com/marshmallow-code/marshmallow/commit/7c5dd90f42722fb0bfc0ec4ede911eee9c5adc89

It now tries to call any object that's callable. This can be troublesome.

In my case I have a `ForeignKey` field which takes relationship attributes from a Django model. My field expects to either get a `RelatedManager` object if it's a `many` relationship, or a model if it's a `one` relationship.

When marshmallow sees the `RelatedManager` it tries to call it triggering the following exception:

```
/lib/python2.7/site-packages/django/db/models/fields/related.py:839: in __call__
    manager = getattr(self.model, kwargs.pop('manager'))
E   KeyError: u'manager'
```

.. as these objects are not supposed to be called, you'd want to do something like `.all()` which my `ForeignKey` field would be doing.

I then looked into how to change this behaviour, and it turned out to be pretty clunky..

I ended up basically having to copy and paste a bunch of code and then override `get_attribute` on my base schema.

``` python
def get_value_but_do_not_call(key, obj, default=missing):
    """Helper for pulling a keyed value off various types of objects"""
    if isinstance(key, int):
        return _get_value_for_key(key, obj, default)
    else:
        return _get_value_for_keys(key.split('.'), obj, default)


def _get_value_for_keys(keys, obj, default):
    if len(keys) == 1:
        return _get_value_for_key(keys[0], obj, default)
    else:
        return _get_value_for_keys(
            keys[1:], _get_value_for_key(keys[0], obj, default), default)


def _get_value_for_key(key, obj, default):
    try:
        return obj[key]
    except (KeyError, AttributeError, IndexError, TypeError):
        try:
            return getattr(obj, key)
        except AttributeError:
            return default
    return default

class BaseSchema(Schema):
    get_attribute = staticmethod(get_value_but_do_not_call)
```

Am I doing something here that's against the grain? Seems like a problem that would be quite common, especially for people using marshmallow with Django models..

**Comment by deckar01** [comment] 2016-07-06 05:15
I suspect django has similar issues with parameters that accept values or callables.

A simple workaround might be to wrap your value in a callable.

``` py
def wrap(obj):
    return (lambda: obj)
```

**Comment by sloria** [comment] 2017-02-18 17:40
Closing as a dupe of #430 ; any further discussion should happen on that issue.

**Closed as completed by sloria** 2017-02-18 17:40 UTC
