### ISSUE TITLE
Temporarily Require a Field

### ISSUE THREAD

**Issue by jeffsawatzky** [marshmallow-code/marshmallow#1361] opened 2019-08-22 16:35 UTC
I have a deeply nested schema, and most of the time the child attributes are not required.

However, occasionally I will need to ensure that one or more of the child attributes are present. Is there a way to do this without having to define multiple schemas for every combination of required attributes?

For example, if I have:
```
class UserDocumentSchema(Schema):
    class UserResourceSchema(Schema):
        class UserAttributesSchema(Schema):
            name = fields.Str()
            password = fields.Str(read_only=True)
            another_attr1 = fields.Str()
            another_attr2 = fields.Str()
            another_attr3 = fields.Str()
            another_attr4= fields.Str()

        id = fields.Str()
        attributes = fields.Nested(UserAttributesSchema)

    resource = fields.Nested(UserResourceSchema)
```

When creating a user I want `name` and `password` to be required but not `id`
When updating the user's name I want `name` and `id` to be required but not `password`
When updating the user's password I want `password` and `id` to be required but not `name`

I know I can create multiple schema's for each combination setting `required=True`, but that seems like a lot of repeated code, and if we change a property name we would need to update it everywhere. It would be nice if there was a way to validate the schema with something like:
```
data = UserDocumentSchema().load(document, required=['resource.attributes.name', 'resource.attributes.password'])
```

Is there something that exists already that does what I want?

**Comment by sloria** [comment] 2019-08-22 16:47
The typical way handle updates is to do the opposite: temporarily make a field optional using [partial](https://marshmallow.readthedocs.io/en/stable/quickstart.html#partial-loading).

**Comment by deckar01** [comment] 2019-08-22 17:42
Duplicate of #1280 and #1296.

Adding meta options and constructor args adds a lot of code and API surface area that will be rarely used. A factory that customizes the schema is probably the most flexible option and is very readable.

```py
def build_user_document_schema(**required):
    class UserDocumentSchema(Schema):
        class UserResourceSchema(Schema):
            class UserAttributesSchema(Schema):
                name = fields.Str(required=required.get('name', True))
                password = fields.Str(read_only=True, required=required.get('password', True))
            
            id = fields.Str(required=required.get('id', True))
            attributes = fields.Nested(UserAttributesSchema)
        
        resource = fields.Nested(UserResourceSchema)
    return UserDocumentSchema

CreateUserSchema = build_user_document_schema(id=False)
UpdateUserSchema = build_user_document_schema(password=False)
ChangePasswordSchema = build_user_document_schema(name=False)
```

**Comment by sloria** [comment] 2019-08-23 23:49
@jeffsawatzky Do either of the above fit your use case?

**Comment by sloria** [comment] 2019-08-26 13:23
Closing for now. Feel free to comment if you have further questions

**Closed as completed by sloria** 2019-08-26 13:23 UTC
Labels: question

**Comment by jeffsawatzky** [comment] 2019-08-26 14:51
Sorry for taking some time to reply.

I don't think those options fit my use case.  Using `partial` means I need to mark all fields as `required`, and then use `partial` to only read the ones I want. However, I am also using apispec to generate OAS docs from the schema's and this means that the OAS docs will now list all fields as required, when they aren't.

I also don't want to litter the OAS doc with a bunch of slight variations of the same schema, but maybe there is no other way.

Perhaps there is another way to run one-off validations? If there was a way to run a validator against a jsonpath string or something that would work too.

**Comment by deckar01** [comment] 2019-08-26 15:12
> I also don't want to litter the OAS doc with a bunch of slight variations of the same schema

OAS requires derived schemas to be declared with inheritance and overridden fields.

https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/

https://github.com/marshmallow-code/apispec/issues/226

https://github.com/timakro/apispec-swaggerinherit
