### ISSUE TITLE
Allow for creating a schema that behaves like Dict field

### ISSUE THREAD

**Issue by ergo** [marshmallow-code/marshmallow#854] opened 2018-06-24 21:32 UTC
Hello,

I think this would be a great addition, if there was a way to somehow create a schema that accepts an object with keys that are unknown upfront but where their values can have a specific field type set.
I don't think there is a way to create a field like that,
So far we can have something like:

    def add_missing_fields(data, original, fields):
        for key, val in original.items():
            if key not in fields:
                data[key] = val
        return data

    class SomeSchema():
        @marshmallow.post_load(pass_original=True)
        def _add_unknown(self, data, original):
            return add_missing_fields(data, original, self.fields)

For adding fields that we don't know upfront But this seems far from ideal solution.

**Comment by lafrech** [comment] 2018-06-24 21:36
Isn't this a dupe of #853?

**Comment by ergo** [comment] 2018-06-24 21:43
Hm, yeah it would seem this would solve my problem, seems the code to handle that is very new and I missed that, and validation part still needs to land I guess :+1:

**Comment by lafrech** [comment] 2018-06-24 21:46
Yes. Let's discuss this in #853. Contribution welcome.

**Closed as completed by lafrech** 2018-06-24 21:46 UTC
