### ISSUE TITLE
Missing first row after dump object

### ISSUE THREAD

**Issue by edgarallanglez** [marshmallow-code/marshmallow#343] opened 2015-11-24 19:03 UTC
people = (1, "edgar", "gonzalez"), (2, "eduardo", "quintero")

selected_list_people = people_schema.dump(people, many=True)

pprint(selected_list_people)
data = [{'id': '2', 'name': 'eduardo', 'lastname': 'quintero'}]

**Comment by jequintero** [comment] 2015-11-25 19:41
Same issue :'(

**Comment by vuonghv** [comment] 2015-11-27 07:36
@edgarallang Show your people_schema class, please.

**Comment by edgarallanglez** [comment] 2015-11-27 16:11
class PeopleSchema(Schema):
    class Meta:
        fields = ('user_id',
                  'name',
                  'lastname')

people_schema = PeopleSchema(many=True)

and this is happening in every schema I've delcared is missing the first row; in the case of a single row when 'many=False' is missing the row too.

**Comment by sloria** [comment] 2015-11-27 17:34
What type is `people` in your original example?

I would guess the issue is caused by this line: https://github.com/marshmallow-code/marshmallow/blob/425e3ad3f2e07cc3c48b4ec7a0887407c80b14a7/marshmallow/schema.py#L714 . Marshmallow inspects the first item in a collection in order to make [implicit field creation](https://marshmallow.readthedocs.org/en/latest/quickstart.html#refactoring-implicit-field-creation) work.

**Comment by edgarallanglez** [comment] 2015-11-27 17:54
I see, but what fields would be implicit, because I am doing the raw query with db.engine.execute('query'), and I'm getting the exact same columns i declared in fields in my schema.

**Comment by edgarallanglez** [comment] 2015-11-27 20:02
is there some parameter to turn that off, because 1.2.6 works as expected for me but option  dateformat doesn work, and the newest version fix that but im missin info after dump :(

**Comment by sloria** [comment] 2015-11-27 20:18
It's not a good long-term solution, but you could cast `people` to a list or tuple before passing it to the Schema.

We can look for a better solution in the meantime. What data structure is `people`?

**Comment by edgarallanglez** [comment] 2015-11-27 20:20
class People(db.Model):

```
__tablename__ = 'people'

user_id = Column(db.Integer, primary_key=True)
name = Column(db.String(STRING_LEN), nullable=False)
lastname = Column(db.String(STRING_LEN), nullable=False)
```

thats my model, i'll try your suggestion, thank you sloria.

**Comment by sloria** [comment] 2015-11-27 20:21
I was referring to the the `people` variable in your original example, not the model class; what is its type?

**Comment by edgarallanglez** [comment] 2015-11-27 21:03
oh sorry, I'm doing a raw query with inner joins to a postgreSQL database, so i'm getting an SQLAlchemy Object.

**Comment by sloria** [comment] 2015-12-06 20:37
@edgarallang I believe https://github.com/marshmallow-code/marshmallow/pull/355 will fix the problem you are having. Can you please verify?

To install marshmallow with the patch:

```
pip install git+https://github.com/jmcarp/marshmallow.git@iter-eager-eval
```

**Comment by edgarallanglez** [comment] 2015-12-07 17:38
Awesome guys, it is fixed :D, thank you for your support!!! @sloria

**Comment by sloria** [comment] 2015-12-08 03:48
Fixed by https://github.com/marshmallow-code/marshmallow/pull/355

**Closed as completed by sloria** 2015-12-08 03:48 UTC
