### ISSUE TITLE
Nested Schema still validated when required fields are missing

### ISSUE THREAD

**Issue by mark0978** [marshmallow-code/marshmallow#504] opened 2016-07-28 16:43 UTC
I thought the whole reason required=True wasn't a validator, but was "special" was so that other validations wouldn't be run when required fields were missing.

```
class InnerForm(Schema):
    first_name = fields.String(required=True, validate=[validate.Length(1, NAME_MAX_LENGTH)])
    last_name = fields.String(required=True, validate=[validate.Length(1, NAME_MAX_LENGTH)])
    username = fields.String(required=True)
    domain_name = fields.String(required=True)
    password = fields.String(required=True)
    password_confirm = fields.String(required=True)

    @validates_schema
    def check_schema(self, item):
         #This gets called even if username is missing and the validation errors dict contains that error.
         pass

class OuterForm(Schema):
    reg_domain_id = fields.Integer(required=True)
    address_id = fields.Integer(required=True)
    payment_profile_id = fields.Integer(required=True)
    sub_plan = fields.String(required=True)
    user_info = fields.Nested(InnerUserInfoForm)
```

When username is missing from the InnerForm, I would expect the validation to halt because required fields are not present.  Instead the schema validation blows up because the field that is required isn't present in the item.

**Comment by maximkulkin** [comment] 2016-08-18 18:23
Duplicate of #319.

**Closed as completed** 2017-01-08 19:44 UTC
