### ISSUE TITLE
ModuleNotFoundError: No module named 'marshmallow.compat' 

### ISSUE THREAD

**Issue by smalekzadeh** [marshmallow-code/marshmallow#1408] opened 2019-09-17 09:05 UTC
We are trying to upgrade from 2.19.2 to 3.1.1 and get the above error . Could you please advice how to get around it.

venv/lib/python3.6/site-packages/flask_apispec/init.py:2: in 
from flask_apispec.views import ResourceMeta, MethodResource
venv/lib/python3.6/site-packages/flask_apispec/views.py:6: in 
from flask_apispec.annotations import activate
venv/lib/python3.6/site-packages/flask_apispec/annotations.py:6: in 
from flask_apispec.wrapper import Wrapper
venv/lib/python3.6/site-packages/flask_apispec/wrapper.py:8: in 
from webargs import flaskparser
venv/lib/python3.6/site-packages/webargs/init.py:8: in 
from webargs.core import dict2schema, ValidationError
venv/lib/python3.6/site-packages/webargs/core.py:23: in 
from marshmallow.compat import iteritems
E ModuleNotFoundError: No module named 'marshmallow.compat'

**Comment by lafrech** [comment] 2019-09-17 10:04
Duplicate of https://github.com/marshmallow-code/webargs/pull/417.

This is not a marshmallow issue. Please update your webargs version.

**Comment by smalekzadeh** [comment] 2019-09-17 10:52
Thanks for your reply lafrech. I have created a clean virtualenv and  pip installed flask-apispec==0.8.2 which resulted in the following libs to be installed:
apispec==2.0.2
Click==7.0
Flask==1.1.1
flask-apispec==0.8.2
itsdangerous==1.1.0
Jinja2==2.10.1
MarkupSafe==1.1.1
marshmallow==3.1.1
pkg-resources==0.0.0
six==1.12.0
webargs==5.5.1
Werkzeug==0.15.6

marshmallow and webargs are the latest versions but I still get the error when I run my test python file which only does importing the lib:

import flask_apispec
from marshmallow.compat import iteritems

error:
  File "test_marsh.py", line 2, in <module>
    from marshmallow.compat import iteritems
ModuleNotFoundError: No module named 'marshmallow.compat'

**Comment by lafrech** [comment] 2019-09-17 10:57
Well, indeed, marshmallow.compat is removed in MA3 since only Python3 is supported, so if you script really reads

```py
import flask_apispec
from marshmallow.compat import iteritems
```

it can't run.

Don't import compat in your script.

**Comment by smalekzadeh** [comment] 2019-09-17 11:25
Sorry lafrech , I think I am missing something here :
"MA3 since Python3 is unsupported"
Does it mean marshmellow 3 doesn't support Python3?
Thanks

**Comment by lafrech** [comment] 2019-09-17 11:57
Sorry, I meant Python 2 unsupported / only Python 3 supported. I fixed my comment.

Anyway, there is no need for this compat layer anymore.

I see no reason to import this in user code. The only reason you'd do that would be to support Python 2 and 3 and use marshmallow's compat layer for convenience, but since marshmallow itself dropped Python 2, you can't do that anymore anyway.

In other words, why do you do that in the first place?

```py
from marshmallow.compat import iteritems
```

If you use a third-party lib that does that, then it ought to be updated as it is not marshmallow 3 compliant.

**Comment by smalekzadeh** [comment] 2019-09-17 14:12
Thanks for clarification lafrech.  We don't do the import in our code and it is a third-party lib (webargs).

**Comment by lafrech** [comment] 2019-09-17 14:19
I saw webargs in the OP but it shouldn't happen in your new virtualenv with webargs 5.5.1.

Can you double-check you're using webargs 5.5.1 and post the traceback again?

**Comment by smalekzadeh** [comment] 2019-09-17 14:31
This is (most of) the pip freeze of the app:
fakeredis==1.0.3
Flask==1.0.2
Flask-And-Redis==1.0.0
flask-apispec==0.8.2
Flask-Cors==3.0.7
Flask-Env==2.0.0
Flask-Login==0.4.1
Flask-Migrate==2.4.0
Flask-PyMongo==2.2.0
Flask-RESTful==0.3.7
Flask-Script==2.0.6
Flask-SQLAlchemy==2.3.2
Flask-Uploads==0.2.1
humanfriendly==4.18
idna==2.8
itsdangerous==1.1.0
Jinja2==2.10
loremipsum==1.0.5
Mako==1.0.8
MarkupSafe==1.1.1
marshmallow==3.1.1
more-itertools==7.0.0
pexpect==4.6.0
pika==1.0.0
pkg-resources==0.0.0
pluggy==0.9.0
ptyprocess==0.6.0
py==1.8.0
pycparser==2.19
PyJWT==1.7.1
pymongo==3.7.2
PyMySQL==0.9.3
pytest==4.4.0
pytest-cov==2.6.1
python-dateutil==2.8.0
python-editor==1.0.4
sortedcontainers==2.1.0
sparkpost==1.3.6
SQLAlchemy==1.3.1
urllib3==1.24.1
uWSGI==2.0.18
webargs==5.5.1
Werkzeug==0.15.1

and this is the error:
    from flask_apispec import ResourceMeta
venv/lib/python3.6/site-packages/flask_apispec/__init__.py:4: in <module>
    from flask_apispec.extension import FlaskApiSpec
venv/lib/python3.6/site-packages/flask_apispec/extension.py:6: in <module>
    from apispec.ext.marshmallow import MarshmallowPlugin
venv/lib/python3.6/site-packages/apispec/ext/marshmallow/__init__.py:40: in <module>
    from .openapi import OpenAPIConverter
venv/lib/python3.6/site-packages/apispec/ext/marshmallow/openapi.py:18: in <module>
    from marshmallow.compat import iteritems
E   ModuleNotFoundError: No module named 'marshmallow.compat'

**Comment by lafrech** [comment] 2019-09-17 14:39
```
venv/lib/python3.6/site-packages/apispec/ext/marshmallow/openapi.py:18: in
from marshmallow.compat import iteritems
```

Clearly, the error is in apispec.

Same debug method: update apispec, retry, pip freeze if it fails.

**Comment by deckar01** [comment] 2019-09-17 14:43
I am unable to repro this in a fresh venv.

**Comment by lafrech** [comment] 2019-09-17 14:47
No, it shouldn't happen in a fresh virtualenv, unless the app or one of its dependencies pins an old apispec version.

**Comment by smalekzadeh** [comment] 2019-09-17 14:50
The error massage was in warargs. I upgraded to latest warlogs (5.5.1) and the error moved to apispec. I upgraded apispec  as you suggested and now no errors. Many thanks lafrech.

**Closed as completed** 2019-09-17 14:52 UTC
Labels: question
